services:
  victory-map:
    build: .
    ports:
      - "3333:80"
    container_name: victory-map-web
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    # Data is copied into the image during build
    # volumes:
    #   - ./data:/usr/share/nginx/html/data:ro
    networks:
      - victory-map-network

networks:
  victory-map-network:
    driver: bridge
